---
title: "Causal Inference for Latent Outcomes Learned with Factor Models"
author: "Jenna Landy"
date: "6/28/2025"
date-modefied: "11/24/2025"
categories: ["mutational signatures", "causal inference", "genomics"]
---

**Citation**: [Jenna M. Landy]{.underline}, Dafne Zorzetto, Roberta De Vito, Giovanni Parmigiani. "Causal Inference for Latent Outcomes Learned with Factor Models." *arXiv preprint* [2506.20549](https://arxiv.org/abs/2506.20549) (2025).

**R Software Package**: [causalLFO](https://github.com/jennalandy/causalLFO)

In many fields---including genomics, epidemiology, natural language processing, social and behavioral sciences, and economics---it is increasingly important to address causal questions in the context of factor models or representation learning. In this work, we investigate causal effects on *latent outcomes* derived from high-dimensional observed data using nonnegative matrix factorization. To the best of our knowledge, this is the first study to formally address causal inference in this setting. A central challenge is that estimating a latent factor model can cause an individual's learned latent outcome to depend on other individuals' treatments, thereby violating the standard causal inference assumption of no interference. We formalize this issue as *learning-induced interference* and distinguish it from interference present in a data-generating process. To address this, we propose a novel, intuitive, and theoretically grounded algorithm to estimate causal effects on latent outcomes while mitigating learning-induced interference and improving estimation efficiency. We establish theoretical guarantees for the consistency of our estimator and demonstrate its practical utility through simulation studies and an application to cancer mutational signature analysis. All baseline and proposed methods are available in our open-source R package, [*causalLFO*](https://github.com/jennalandy/causalLFO).

------------------------------------------------------------------------

Advised by Giovanni Parmigiani, PhD\
Department of Data Science, Dana Farber Cancer Institute\
Department of Biostatistics, Harvard T.H. Chan School of Public Health
